<a href="https://colab.research.google.com/github/BiduytMondal/hello.py/blob/main/saloyr_python123.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Deleting elements
t = ['a','b','c']
x=[t.pop(1)]
print(t)

['a', 'c']


In [2]:
from statistics import median

import numpy as np
a=[1,2,3]
b=[4,5,6]
sum = a+b

print(f"concatinate:{sum}")#SUMATION IS CONCATINATE
A = np.array([3,4,5,5,7])
B = np.array([3,4,5,6,7])
print(f"summation the array:{A+B}")
c = [[1,2],[3,4],[5,6]]
print(c)
print(np.zeros((4,4 )))
d = np.linspace(1,10,2)
print(d)
f = np.array([1,2,3,4,5,6,7,8,9])
g=f.reshape(3,3)
print(f"slice{f[2:6]}")
h=np.array([[1,2],[3,4],[5,6]])
i=np.array([[3,4],[5,6],[1,2]])
print(h[2,1])
print(h[:2,1])
print(f"serial print{h[1:2, : ]}")
print(h +5)
print(h[h>3])
print(f"vartical line:{np.vstack(i+h)}")
print(np.hstack(i+h))
print(np.split(f,3))
print(np.sum(h,axis=1))
k=np.array([1,2,3,4,5,6])
print(np.sum(k))
print(np.mean(k))
print(np.std(k))
print(np.var(k))
print(np.median(k))
print(np.random.rand(1,4))
print("identity matix :",np.eye(5))
print(np.split(k,2))
print(np.sum(h,axis=1))
print(np.cumsum(k))
print(np.random.randint(1,50,(4,5)))
print(np.transpose(h))


concatinate:[1, 2, 3, 4, 5, 6]
summation the array:[ 6  8 10 11 14]
[[1, 2], [3, 4], [5, 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[ 1. 10.]
slice[3 4 5 6]
6
[2 4]
serial print[[3 4]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[4 5 6]
vartical line:[[ 4  6]
 [ 8 10]
 [ 6  8]]
[ 4  6  8 10  6  8]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[ 3  7 11]
21
3.5
1.707825127659933
2.9166666666666665
3.5
[[0.12807332 0.29317588 0.81529055 0.79299024]]
identity matix : [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[array([1, 2, 3]), array([4, 5, 6])]
[ 3  7 11]
[ 1  3  6 10 15 21]
[[24 45 34  9  2]
 [10 15  6 21 33]
 [33  1  1 42 48]
 [43 11 30 12 27]]
[[1 3 5]
 [2 4 6]]


In [3]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'London', 'Paris']}
df = pd.DataFrame(data)

# Select the 'Name' column
print(df['Name'])

# Select 'Name' and 'Age' columns
print(df[['Name', 'Age']])
#select 'name' and 'city' columns
print(df[['Name','City']])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
      Name      City
0    Alice  New York
1      Bob    London
2  Charlie     Paris
